### PR TITLE
Notate default key bindings in readme.

### PR DESCRIPTION
**Pull request by kindaro**
Hey. I notice the default key bindings are far from obvious, so after looking them up, rather than whining in Issues, I decided to write them down to the readme.

### CODE REVIEW

**Comment by olynch** [comment]
Sure! Just don't expect the current default key-bindings to stay the same -- this is really heavy alpha. I'll try to keep the documentation updated in the future though! Also, I'm wondering how you found ige, and how you are using it. Any feedback is super welcome!

**Comment by kindaro** [comment]
I'm studying graphs, so I searched over Hackage for interesting graph related projects.

Sometimes I need to quickly put together an example graph to study a case for this or that algorithm. So, after I figure out a nice way to export / import graphs between IGE and my haskell drafts, I could use it rather than compose examples by hand.

**Comment by olynch** [comment]
Would you like me to help you figure out how to do that? What format do you want it for your haskell drafts?

**Comment by kindaro** [comment]
I see it exports graph data in JSON, which is good for general interoperability, but I wonder if we can optionally export the same data in more haskelly a serialization. Like, typed. I don't know what the format could be.

**Comment by kindaro** [comment]
I think maybe we could separate the part of `ige` responsible for the import/export of graph files, to a small library that can then be imported to any Haskell project (including `ige` itself) and this way immediately make any 2 such projects compatible. We can then optimize the format ad nauseam and write converters to the data native to `fgl` or any other graph library.

**Comment by olynch** [comment]
I like the idea of separating out the serialization/deserialization. That would also make it nicer to support, say, graphml or gexf or gml for import into other programs.
In terms of making the serialization more haskelly/typed, I'm not exactly sure what the purpose of this would be, because ultimately the type of the serialization is ByteString and it's on the library to decide what to do with that. I am definitely willing to serialize to a format other than JSON (certainly not my favorite format), but I'd have to have a good reason to.

**Pull request merged**
